// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedFrex.DataAccess;

#nullable disable

namespace SchedFrex.DataAccess.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    [Migration("20260302071507_SlotNotNullableNow")]
    partial class SlotNotNullableNow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.EntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("EntryEntity");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.ProblemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.UserEntity", "User")
                        .WithMany("Calendars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.EntryEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.CalendarEntity", "Calendar")
                        .WithMany("Entries")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SchedFrex.DataAccess.Entities.TimeIntervalEntity", "Slot", b1 =>
                        {
                            b1.Property<Guid>("EntryEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("End");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Start");

                            b1.HasKey("EntryEntityId");

                            b1.ToTable("EntryEntity");

                            b1.WithOwner()
                                .HasForeignKey("EntryEntityId");
                        });

                    b.Navigation("Calendar");

                    b.Navigation("Slot")
                        .IsRequired();
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.ProblemEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.UserEntity", "User")
                        .WithMany("Problems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SchedFrex.DataAccess.Entities.TimeIntervalEntity", "TimeIntervals", b1 =>
                        {
                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("End");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Start");

                            b1.HasKey("ProblemId", "Id");

                            b1.ToTable("ProblemIntervals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.Navigation("TimeIntervals");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.UserEntity", b =>
                {
                    b.Navigation("Calendars");

                    b.Navigation("Problems");
                });
#pragma warning restore 612, 618
        }
    }
}
