// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedFrex.DataAccess;

#nullable disable

namespace SchedFrex.DataAccess.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    [Migration("20260227073114_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("SlotId");

                    b.ToTable("CalendarEntryEntity");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.PriorityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PriorityEntity");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.ProblemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid>("PriorityEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PriorityEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.TimeIntervalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProblemEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProblemEntityId");

                    b.ToTable("TimeIntervalEntity");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntryEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.CalendarEntity", "Calendar")
                        .WithMany("Entries")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedFrex.DataAccess.Entities.TimeIntervalEntity", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.ProblemEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.PriorityEntity", "PriorityEntity")
                        .WithMany()
                        .HasForeignKey("PriorityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedFrex.DataAccess.Entities.UserEntity", "User")
                        .WithMany("Problems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriorityEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.TimeIntervalEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.ProblemEntity", null)
                        .WithMany("TimeIntervals")
                        .HasForeignKey("ProblemEntityId");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.UserEntity", b =>
                {
                    b.HasOne("SchedFrex.DataAccess.Entities.CalendarEntity", "Calendar")
                        .WithOne("User")
                        .HasForeignKey("SchedFrex.DataAccess.Entities.UserEntity", "CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.CalendarEntity", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.ProblemEntity", b =>
                {
                    b.Navigation("TimeIntervals");
                });

            modelBuilder.Entity("SchedFrex.DataAccess.Entities.UserEntity", b =>
                {
                    b.Navigation("Problems");
                });
#pragma warning restore 612, 618
        }
    }
}
